version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: taskmanager_mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: TaskManagerDB_Dev
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - taskmanager_network
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: taskmanager_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=TaskManagerDB_Dev;User=root;Password=yourpassword;
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - mysql
    networks:
      - taskmanager_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: taskmanager_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
    networks:
      - taskmanager_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  taskmanager_network:
    driver: bridge 